# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
